apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend-deployment
    spec:
      containers:
      - name: {{ .Release.Name }}-backend-deployment
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-root-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-root-password
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-mongo-config
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-backend-deployment
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend-deployment
    spec:
      containers:
      - name: {{ .Release.Name }}-frontend-deployment
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-frontend-deployment
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    nodePort: {{ .Values.frontend.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongo-pvc
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: {{ .Values.mongo.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongo-secret
              key: mongo-root-password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: {{ .Values.mongo.port }}
    protocol: TCP
    targetPort: {{ .Values.mongo.port }}
