apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 100M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Adjust access mode based on your requirements
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/worker/ # Replace with your local path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker
