apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 50M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
