backend:
  image: manjunath728/todo-server:97
  port: 5000
  replica : 3

mongo:
  port: 27017
  replica : 1

  persistentVolumeClaim:
    storage: 50M
    accessMode: ReadWriteOnce

  secret:
    mongoRootUsername: cm9vdA==
    mongoRootPassword: cjAwdA==

  configMap:
    databaseUrl: mongodb-service
