apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
type: Opaque
data:
  mongo-root-username: {{ .Values.mongo.secret.mongoRootUsername }}
  mongo-root-password: {{ .Values.mongo.secret.mongoRootPassword }}
