backend:
  image: manjunath728/todo-server:82
  port: 5000

mongo:
  port: 27017

  persistentVolumeClaim:
    storage: 50M
    accessMode: ReadWriteOnce

  secret:
    mongoRootUsername: cm9vdA==
    mongoRootPassword: cjAwdA==

  configMap:
    databaseUrl: mongodb-service
